language: python
python:
  - "3.6"

cache: pip # enable cache for "$HOME/.cache/pip" directory

env:
  global:
  - ENCRYPTION_LABEL: ec68c19ba263


before_install:
  - export CFLAGS=-O0 # considerably speed-up build time for pip packages (especially lxml), optimizations doesn't matter for ci
  - pip install pyyaml

install:
  - pip install -r requirements.txt

script: bash ./.ci/deploy.sh

after_script:
  - sleep 10 # helps travis finish logging


## Builds for pull requests skip the deployment step altogether
#deploy:
## Continious deployment of most recent spoiler.xml
#  - provider: releases
#    api_key:
#      secure: Bin220gU9Re176T/1bIaX/rhGB+uEaw13aoB2/ir0ePHQB0ihasEJcsgmlN8kz93KSN6vp4y2HwMLnz3t7Pn0amTV8QVL/AlOOzjbq8m/1kYTbXdPlYnMsosZPVFLHRan4LEGFsovRia6LO4p9fqC8BDgQl89W/88PlYAMWzao5jTyKKHp8o+sioYhKj9D+86lxLYspQ+6SN0HOCnF2MZ/vZtxbY32ituswAc/sJK1MtZ/PExoMe1nSI2iKCaatXyKA+FVCUNLHRAu4LgB1GfJCLpmlPbvjud8A6WAKNF6poNCvFck+Ox56tt4bw3ggR5W9kTEhvX74l6AEeC7Qz6bHjh1CEngrqFjyaHy25CcygWgagf0DUsvyGRS0RqEx4bz9psD09d+oWihdkJMfa5kRzXtVQD8sxDgsBqEz/DjsMIlf/L5ISSa7lAYiqq65ELpezBFOlvEZ9avOYLcZc7m5/5ZhtcA4HPSqzfn2nhkPpeggBKufMdyc8JIDkvs/JlFsNu46QVvugjbdGvtb4SlQK310py0TOA6nYt7WntDhX3SukKAeh6oHjZaL5aeoSBhnlQRgJfDBqI3+7anLatD30uEKCMp5sWcLrjB1HO9ZH5nceWBg4cMKJvI/zT77h96fCy7uMkPNt867GP8O9KkWVWzxGBkpIdstigNWfT5g=
#    name: "Current output"
#    body: "![](https://img.shields.io/badge/dynamic/xml.svg?label=Contained%20sets&colorB=4ac41d&url=https%3A%2F%2Fraw.githubusercontent.com%2FCockatrice%2FMagic-Spoiler%2Ffiles%2Fspoiler.xml&query=%2F%2Flongname)<br> Most recent <kbd>spoiler.xml</kbd> (put date here)"
#    file_glob: true
#    file: out/spoiler.xml
#    skip_cleanup: true
#    overwrite: true
#    draft: false
#    prerelease: true
#    on:
#      repo: Cockatrice/Magic-Spoiler
#      branch: master

## Deployment of fully spoiled sets for archive reasons (on tags)
#  - provider: releases
#    api_key:
#      secure: Bin220gU9Re176T/1bIaX/rhGB+uEaw13aoB2/ir0ePHQB0ihasEJcsgmlN8kz93KSN6vp4y2HwMLnz3t7Pn0amTV8QVL/AlOOzjbq8m/1kYTbXdPlYnMsosZPVFLHRan4LEGFsovRia6LO4p9fqC8BDgQl89W/88PlYAMWzao5jTyKKHp8o+sioYhKj9D+86lxLYspQ+6SN0HOCnF2MZ/vZtxbY32ituswAc/sJK1MtZ/PExoMe1nSI2iKCaatXyKA+FVCUNLHRAu4LgB1GfJCLpmlPbvjud8A6WAKNF6poNCvFck+Ox56tt4bw3ggR5W9kTEhvX74l6AEeC7Qz6bHjh1CEngrqFjyaHy25CcygWgagf0DUsvyGRS0RqEx4bz9psD09d+oWihdkJMfa5kRzXtVQD8sxDgsBqEz/DjsMIlf/L5ISSa7lAYiqq65ELpezBFOlvEZ9avOYLcZc7m5/5ZhtcA4HPSqzfn2nhkPpeggBKufMdyc8JIDkvs/JlFsNu46QVvugjbdGvtb4SlQK310py0TOA6nYt7WntDhX3SukKAeh6oHjZaL5aeoSBhnlQRgJfDBqI3+7anLatD30uEKCMp5sWcLrjB1HO9ZH5nceWBg4cMKJvI/zT77h96fCy7uMkPNt867GP8O9KkWVWzxGBkpIdstigNWfT5g=
#    body: "Thanks to everyone who assisted with code or provided data corrections."
#    file_glob: true
#    file: out/*.xml
#    skip_cleanup: true
#    overwrite: true
#    draft: true
#    prerelease: false
#    on:
#      tags: true
#      repo: Cockatrice/Magic-Spoiler
#      branch: master
#      condition: $TRAVIS_TAG =~ ^[0-9]     # regex to skip automatically added "untagged" tags from continious deployment "Current output"


notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/691b9acffe1def5f9d6b
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
